apiVersion: v2
name: onecx-product-store-ui
version: ${project.version}
description: Helm chart for onecx-product-store-ui deployment.
home: https://github.com/onecx/onecx-product-store-ui
keywords:
  - onecx
  - portal
  - 1000kit
  - menu
  - microfrontend
sources:
  - https://github.com/onecx/onecx-product-store-ui.git
maintainers:
  - name: OneCX Developer Team
    email: tkit_dev@1000kit.org
dependencies:
  # https://gitlab.com/1000kit/infra/helm/angular.git
  - name: angular
    version: ^0
    repository: https://harbor.1000kit.org/chartrepo/1000kit/
    # repository: file:///home/mat/projects/tkit/helm/angular
    alias: app
